// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DumpDB.Models
{
    public partial class Bornes
    {
        public int Id { get; set; }
        public string BorneType { get; set; }
        public string Description { get; set; }
        public int Kwatt { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public int Capacity { get; set; }
        public string BorneStatus { get; set; }
        public decimal Location { get; set; }
        public string ChargerTypeId { get; set; }
        public string Logitude { get; set; }
        public string Latitude { get; set; }
    }
}