// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DumpDB.Models
{
    public partial class Chargertype
    {
        public string Id { get; set; }
        public string ChargerType1 { get; set; }
        public string EstimatedTime { get; set; }
        public string ConnectorType { get; set; }
        public int? Status { get; set; }
    }
}