// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DumpDB.Models
{
    public partial class Carrepair
    {
        public int Id { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Longitute { get; set; }
        public string Latitude { get; set; }
        public string ServiceOffered { get; set; }
        public int? UserId { get; set; }
    }
}